import Header from '@/Components/Header';
import Footer from '@/Components/Footer';
import Script from 'next/script';
import './globals.scss';
import '../../public/assets/scss/style.scss';
import '../../public/assets/css/vendors/bootstrap.min.css';
import '../../public/assets/css/vendors/jos.css';
import '../../public/assets/css/vendors/swiper-bundle.min.css';
import '../../public/assets/css/style.css';
import '../../public/assets/fonts/iconfonts/font-awesome/stylesheet.css';

import 'react-accessible-accordion/dist/fancy-example.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />

        <Script
          src="/assets/js/vendors/bootstrap.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/assets/js/vendors/counterup.js"
          strategy="lazyOnload"
          type="module"
        />
        <Script src="/assets/js/vendors/fsLightbox.js" strategy="lazyOnload" />
        <Script src="/assets/js/vendors/jos.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/vendors/popper.min.js" strategy="lazyOnload" />
        <Script
          src="/assets/js/vendors/swiper-bundle.min.js"
          strategy="beforeInteractive"
        />
        <Script src="/assets/js/main.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
